language: go

go:
  - 1.11.5

install:
  - go get github.com/go-telegram-bot-api/telegram-bot-api
  - go get github.com/jinzhu/gorm
  - go get github.com/lib/pq

services:
  - postgresql

before_script:
  - psql -c 'create database test;' -U postgres
  - export MEANS_DB_USERNAME=postgres
  - export MEANS_DBNAME=test
addons:
  postgresql: "11"
  apt:
    packages:
    - postgresql-11
    - postgresql-client-11
